host = "0.0.0.0"
port = 80
enable_logging = true
root_dir = "/var/www/html"
fallback_document = "404.html"

[headers]
"Cache-Control" = "public, max-age=259200, stale-while-revalidate=86400, stale-if-error=86400"
"X-Frame-Options" = "DENY"
"X-XSS-Protection" = "1; mode=block"

[rewrites]
"/rick" = "/never-gonna-give-you-up"
"/stack" = "/blog/my-stack-2024"

[redirects]
"/never-gonna-give-you-up" = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
"/x" = "https://twitter.com/trulyao"
"/github" = "https://github.com/aosasona"
"/statsfm" = "https://stats.fm/trulyao"
