root = "."
domain_names = ["preview.trulyao.dev"]
fallback_file = "404.html"
default_index_file = "index.html"

[rewrites]
"/rick" = "/never-gonna-give-you-up"
"/stack" = "/blog/my-stack-2024"

[redirects]
"/never-gonna-give-you-up" = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
"/x" = "https://twitter.com/trulyao"
"/github" = "https://github.com/aosasona"
"/statsfm" = "https://stats.fm/trulyao"
